//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ggggf
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Время.
    /// </summary>
    // *** Start programmer edit section *** (Время CustomAttributes)

    // *** End programmer edit section *** (Время CustomAttributes)
    [ICSSoft.STORMNET.StoreInstancesInType(typeof(datetime-local), typeof(DataTime))]
    public class Время
    {
        
        private System.DateTime fВремя;
        
        private IIS.Ggggf.Класс fКласс;
        
        // *** Start programmer edit section *** (Время CustomMembers)

        // *** End programmer edit section *** (Время CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Время.Время CustomAttributes)

        // *** End programmer edit section *** (Время.Время CustomAttributes)
        public virtual System.DateTime Время
        {
            get
            {
                // *** Start programmer edit section *** (Время.Время Get start)

                // *** End programmer edit section *** (Время.Время Get start)
                System.DateTime result = this.fВремя;
                // *** Start programmer edit section *** (Время.Время Get end)

                // *** End programmer edit section *** (Время.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Время.Время Set start)

                // *** End programmer edit section *** (Время.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Время.Время Set end)

                // *** End programmer edit section *** (Время.Время Set end)
            }
        }
        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Время.Класс CustomAttributes)

        // *** End programmer edit section *** (Время.Класс CustomAttributes)
        public virtual IIS.Ggggf.Класс Класс
        {
            get
            {
                // *** Start programmer edit section *** (Время.Класс Get start)

                // *** End programmer edit section *** (Время.Класс Get start)
                IIS.Ggggf.Класс result = this.fКласс;
                // *** Start programmer edit section *** (Время.Класс Get end)

                // *** End programmer edit section *** (Время.Класс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Время.Класс Set start)

                // *** End programmer edit section *** (Время.Класс Set start)
                this.fКласс = value;
                // *** Start programmer edit section *** (Время.Класс Set end)

                // *** End programmer edit section *** (Время.Класс Set end)
            }
        }
    }
}
