//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ggggf
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Класс.
    /// </summary>
    // *** Start programmer edit section *** (Класс CustomAttributes)

    // *** End programmer edit section *** (Класс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассE", new string[] {
            "прикол as \'Прикол\'"})]
    [View("КлассL", new string[] {
            "прикол as \'Прикол\'"})]
    public class Класс : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fприкол;
        
        // *** Start programmer edit section *** (Класс CustomMembers)

        // *** End programmer edit section *** (Класс CustomMembers)

        
        /// <summary>
        /// прикол.
        /// </summary>
        // *** Start programmer edit section *** (Класс.прикол CustomAttributes)

        // *** End programmer edit section *** (Класс.прикол CustomAttributes)
        public virtual System.DateTime прикол
        {
            get
            {
                // *** Start programmer edit section *** (Класс.прикол Get start)

                // *** End programmer edit section *** (Класс.прикол Get start)
                System.DateTime result = this.fприкол;
                // *** Start programmer edit section *** (Класс.прикол Get end)

                // *** End programmer edit section *** (Класс.прикол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Класс.прикол Set start)

                // *** End programmer edit section *** (Класс.прикол Set start)
                this.fприкол = value;
                // *** Start programmer edit section *** (Класс.прикол Set end)

                // *** End programmer edit section *** (Класс.прикол Set end)
            }
        }
        
        // *** Start programmer edit section *** (Класс.Dhtvz CustomAttributes)

        // *** End programmer edit section *** (Класс.Dhtvz CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual System.DateTime Dhtvz()
        {
            // *** Start programmer edit section *** (Класс.Dhtvz method implementation)

            return null;
            // *** End programmer edit section *** (Класс.Dhtvz method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлассE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассE", typeof(IIS.Ggggf.Класс));
                }
            }
            
            /// <summary>
            /// "КлассL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассL", typeof(IIS.Ggggf.Класс));
                }
            }
        }
    }
}
